# Generated by Django 4.2.2 on 2023-06-18 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreC', models.CharField(max_length=50)),
                ('nombreAus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CampeonatoEquip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losequipos', to='futbolec.campeonato')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoFut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('siglas', models.CharField(max_length=30)),
                ('usernameTw', models.CharField(max_length=30)),
                ('campeonatoEquip', models.ManyToManyField(through='futbolec.CampeonatoEquip', to='futbolec.campeonato')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('posicion', models.CharField(max_length=30)),
                ('numeroCam', models.IntegerField()),
                ('sueldo', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losjugadores', to='futbolec.equipofut')),
            ],
        ),
        migrations.AddField(
            model_name='campeonatoequip',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losequipos', to='futbolec.equipofut'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='campeonatoequip',
            field=models.ManyToManyField(through='futbolec.CampeonatoEquip', to='futbolec.equipofut'),
        ),
    ]
